services:
  - type: web
    name: mini-erp-crm-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: CORS_ORIGIN
        value: https://mini-erp-crm-blond.vercel.app
      - key: DATABASE_URL
        sync: false
